name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.6
        with:
          cli: 1.12.0.1479

      - name: Run tests
        run: clojure -X:test

      - name: Build uberjar
        run: clojure -T:build uber

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kongeor/kino
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          platforms: linux/amd64,linux/arm64
