services:
  kino_db:
    image: 'postgres:15.7'
    container_name: kino_db

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
